name: Check Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Check Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'core-api/package-lock.json'

      - name: Install dependencies
        run: |
          cd core-api
          npm ci --ignore-scripts
        shell: bash

      - name: Run tests
        run: |
          cd core-api
          npm run test
        shell: bash
